Algoritmo "ExemploSE"  //nome do programa
Var
nome:caractere;
salario:real;
Inicio
escreva("Digite su nome: ")
leia(nome)
escreva("Digite seu salário: ")
leia(salario)
se (salario > 1200) entao
escreval (nome, " seu saláro é maior que o salário mínimo!!!")
senao
se (salario = 1200) entao
escreval (nome, " seu Salário é igual ao saláro mínimo!!!")
senao
escreval( nome, " seu Salário é menor que o salário mínimo!!!")
fimse
fimse
Fimalgoritmo